### ISSUE TITLE
Documentation Request: Include instructions on how to fine tune pre-existing weights

### ISSUE THREAD

**Issue by michael-conrad** [Tomiinek/Multilingual_Text_to_Speech#14]
Please include instructions on how to resume training starting with your 70k iteration weights.

Would it be possible to add additional languages as part of a fine tuning process?

**Comment by padmanabhankrishnamurthy** [comment]
Hi,

Just wanted to know if there has been any movement on this, and if there's a clearer path to fine-tuning the model with new languages / speakers now?

Thanks!

**Comment by Tomiinek** [comment]
Hello, I am sorry guys, no movement. The training script is also not very fine-tuning friendly :pensive:

**Comment by padmanabhankrishnamurthy** [comment]
Thanks for the reply! 

I've been trying to adapt the current code for fine-tuning on the LJSpeech dataset, i.e, adding support for English and for the LJSpeech speaker. 

My approach currently involves freezing all parameters of the character encoder using param.requires_grad=False, and just training only the language encoder and the speaker encoder. Since there is only one speaker in the LJSpeech dataset, I have even set multi_speaker to False to turn off the adversarial speaker classifier. My model has been training for around 2 days (150 epochs on only the LJSpeech dataset), and while speech is starting to be generated in the LJSpeech speaker's voice, the model appears to have lost all information about other speakers. Consequently, feeding in any speaker id produces speech only in the LJSpeech speaker's voice.

Does this approach seem right to you?

**Comment by Tomiinek** [comment]
Ou, interesting! 

Just to clarify ... Are you useing `GeneratedConvolutionalEncoder` as the encoder? If so, how did you add English? Did you make the inner embedding bigger and trainable while fixing the rest of the encoder parameters?
Also, how do you load the pre-trained model or treat the speaker embeddings? Because if you set `multi_speaker=False` the checkpoint has some extra paramters (and maybe the decoder expects larger inputs?)

Fixing decoder seems ok, but you cannot expect that the resulting voice will be exactly matching Linda. Maybe, you can try

**Comment by padmanabhankrishnamurthy** [comment]
Hi,

So unfortunately, our fine-tuning experiments didn't work out.
But we're trying another line of experiments wherein we're attempting to get a single English speaker to speak in another language (say for example, German). In this case, since the use-case employs only one English speaker, is it sufficient to train the model using English recordings of only the target speaker, and German recordings of multiple other speakers? I.e, am I right in concluding that recordings of multiple English speakers are unnecessary, since we wish to synthesise German speech in only one particular English voice?

Thanks!
