### ISSUE TITLE
CPU Bottleneck?

### ISSUE THREAD

**Issue by michael-conrad** [Tomiinek/Multilingual_Text_to_Speech#15]
I'm working on seeing what can be done with smaller batch sizes with the existing data sets, and currently have my batch size set to '10'. This results in a bit over 4GB memory being allocated on my NVIDIA GPU which only has 5GB-5.5GB available memory.

I'm using pre-generated spectrograms.

However, the GPU usage seems a tad low and the CPU usage high.

Right now top shows python at 100% CPU utilization. With GPU usage fluctuation between about 45% to 88%.

Is there some other data that can be pre-calculated and cached to reduce python bottlenecking on the CPU?

**Comment by Tomiinek** [comment]
There are no extra CPU-expensive operations during training. It has to load a few spectrograms from disk to construct a batch and move it to GPU memory (note that the `train.py` script has the `loader_workers` parameter). 

When training on two 8GB GTX1080s with batch size 64 (in parallel), I get the GPU utilization fluctuating between 50% and 94% Smaller batches result in more memory transfers and your GPU probably waits more time.

**Comment by leijue222** [comment]
>  (note that the train.py script has the loader_workers parameter).

When I trained for 9 hours, the epoch was 22, and the step was 8k, the process was interrupted by the error of：`RuntimeError: DataLoader worker (pid 16904) is killed by signal: Aborted.`

Therefore, I restore training from a checkpoint and set `loader_workers=0`.
I hope the training will not be interrupted anymore. I was sleeping when the training was interrupted. I didn’t discover this error in time so that I wasted a whole night of training time.:sob:
