### ISSUE TITLE
problem training

### ISSUE THREAD

**Issue by andy311p** [Tomiinek/Multilingual_Text_to_Speech#23]
I want to train using generated_training on two languages "russian"+"french". 
I downloaded CSS10 data from links you gave on these languages, ran the prepare_css_spectrograms.py, created a custom generated_training.json file

I run train.py on 2 GPUs

I have several issues:
1. In addition, its been running for 3 hours but nothing seems to happen (tensorboard is empty). is that normal?

2. How long does a training like that should take?

PS. I switched tensorboard to tensorboardX in the utils/logging.py due to an issue I had. Don't know if it has any affect...

**Comment by Tomiinek** [comment]
Hello :slightly_smiling_face: 

So do I understand it correctly that you are training with the CSS10 on Russian and French? No other data?

1. Hm, no it isn't. There is a pre-proccessing at the begining of training (calculating per-channel spectrogram characteristics because of normalization), but it usually takes just a few minutes.
2. If I remember correctly, I run my models on the whole CSS10 + CV until convergence and it took something like 5-6 days on two GTX1080. However, it produced intelligible speech pretty soon.

Could you share the config file?
