### ISSUE TITLE
Google Colab For Training and Synthesis custom Audio sets on Weak Computers?

### ISSUE THREAD

**Issue by krigeta** [Tomiinek/Multilingual_Text_to_Speech#47]
Hello, Is it possible for you to make Google colabs for Training and Synthesis our own custom audio files uploaded on Gdrive? it would be so easy and awesome to use it on weak computers.

Note: the current colabs are working on pre-trained models and they are working perfectly but it would be so awesome if you will make colabs for Training and Synthesis our new models based on our custom multilingual voices.

Thank you

**Comment by Tomiinek** [comment]
Hello, the current colabs use pre-trained models as you say, but you can switch to your own models easily, just download your models instead of the pre-trained :slightly_smiling_face: 

Change the url in  `! curl -O -L "https://github.com/Tomiinek/Multilingual_Text_to_Speech/releases/download/v1.0/$tacotron_chpt"` to whatever you want.

**About the training colab:** I hope colab has some restrictions for the time you can run your scripts (like a few hours) because it is not intended to be used for long-time training. I trained the models several days, so this might be a problem. Moreover, there are restrictions for the disk space usage and all the audio data used for training are pretty large, this is another problem. Are you aware of it?

**Comment by krigeta** [comment]
> Hello, the current colabs use pre-trained models as you say, but you can switch to your own models easily, just download your models instead of the pre-trained 🙂
> 
> Change the url in `! curl -O -L "https://github.com/Tomiinek/Multilingual_Text_to_Speech/releases/download/v1.0/$tacotron_chpt"` to whatever you want.
> 
> **About the training colab:** I hope colab has some restrictions for the time you can run your scripts (like a few hours) because it is not intended to be used for long-time training. I trained the models several days, so this might be a problem. Moreover, there are restrictions for the disk space usage and all the audio data used for training are pretty large, this is another problem. Are you aware of it?

Thank you so much for your precious reply.

I was checking both of the collab multitraining and code switching and I am amazed of what this awesome project can able to do.

My goal is to make A japanese speaker able to speak English and Hindi(but for learning purpose lets use german and chinese because they are available and a part of this project already).

Answer to the second question is that yes i know the limitations of google colab but I am using it for testing purpose only because my PC is potato and soon I will able to make a good PC but till then I want to try things out in google colab notebook.

So may you please guide me on how can I able to reach my desired Goal by using the current CSS10 datasets but everything from scratch.

Please help 🙏
