### ISSUE TITLE
HighwayConvBlockGenerated class return size miss match error 

### ISSUE THREAD

**Issue by Thien223** [Tomiinek/Multilingual_Text_to_Speech#57]
Thank for your efforts. 

Could you please tell me which task this code does in the "HighwayConvBlockGenerated" class?
When training using my custom data, this return error that says the x's dimension and (h2 * p)'s dimension miss match.
the (h2 * p)'s dimension is a half of x, so they could not be added.
The error: `RuntimeError: The size of tensor a (3584) must match the size of tensor b (1792) at non-singleton dimension 1`

```
def forward(self, x):
            e, x = x
            _, h = super(HighwayConvBlockGenerated, self).forward((e, x))
            chunks = torch.chunk(h, 2 * self._groups, 1)
            h1 = torch.cat(chunks[0::2], 1)
            h2 = torch.cat(chunks[1::2], 1)
            p = self._gate(h1)
            return e, h2 * p + x * (1.0 - p)

**Comment by Tomiinek** [comment]
Hello,

Could you print shapes of `x`,`h2`, and most importantly `self._groups` after chunking? `h` should be two times larger than `x`, so after chunking to odd and even things everything should be ok. 

I guess that the problem is caused by invalid `self._group` which should be the same as the number of languages in your batch when using the perfect sampler (the inputs for all languages are encoded in parallel using the grouped convolutions to avoid a need for multiple encoder forward passes).

**Comment by Thien223** [comment]
I have 7 languages in dataset, so self._group variable is 7. Is that true?

As you said that the self._group is the number of language in the batch only. But I have traced in the code and think that self._group is language number from hp.language_number (not in the batch). Is there something i have missed?

Thank you so much, sir.
