### ISSUE TITLE
Model is much slower on CPU

### ISSUE THREAD

**Issue by aj7tesh** [Tomiinek/Multilingual_Text_to_Speech#72]
Hi I was trying to use the GEN model which you trained. However, I find it very slower in speech synthesis even for a small sentence of 10 words, on CPU. Is there a way to fasten it up other than moving onto GPU?
Thank you

**Comment by king-dahmanus** [comment]
Also, please, contributors, please look at my sapification issue. I want
the voices available in this TTS engine to be used by a screen reader on
Windows, along with other sappy compatible apps.. it's actually s, a, p, I.
But because I am using a speech dictation feature from Google on android,
it writes it as sappy. But, you get my idea, speech application programming
interface version 5.0. thanks for reading!

**Comment by king-dahmanus** [comment]
Voice typing and why I mentioned this in this specific topic and not any
other one, is because being fast and responsive is one of the requirements
for use and snappy.

**Comment by aj7tesh** [comment]
also is english not available for code switching ?

**Comment by Tomiinek** [comment]
Hello, @king-dahmanus , replied in #69

**Comment by Tomiinek** [comment]
> Hi I was trying to use the GEN model which you trained. However, I find it very slower in speech synthesis even for a small sentence of 10 words, on CPU. Is there a way to fasten it up other than moving onto GPU?

This is expected, CPU is of course much slower. If you want to make it faster on CPUs, there are some tricks. First, you can convert the code and model to [Torchscript](https://pytorch.org/docs/stable/jit.html). Second, you can try out some model [pruning techniques](https://pytorch.org/tutorials/intermediate/pruning_tutorial.html).

**Comment by king-dahmanus** [comment]
hey tom, I replied to #69 as well
