### ISSUE TITLE
Wavernn vocoder retraining

### ISSUE THREAD

**Issue by anselmerobert** [Tomiinek/Multilingual_Text_to_Speech#8]
Thank you for the great job.
I would like to retrain the wavernn vocoder (with the generated_training configuration) and I'm not sure how to proceed.
Have you used ground truth mel coefficients as inputs or have you used ground truth aligned mel coefficients?
In the later case (gta): what is the sequence of commands to use? The gta.py script does not take the json parameters file as the train.py script does (thanks to the hyper_parameter argument), so it seems to only be usable with the default (ljspeech) configuration. Moreover it generates .npy files for the generated ground truth aligned mel coefficients with names that do not match the wav files names, where the preprocess.py script in the WaveRnn project expects the two files (wav and mel .npy files) to have the same root.
Thanks again

**Comment by Tomiinek** [comment]
Hi!

I used GTA mel spectrograms for WaveRNN training. 

The `gta.py` script takes a checkpoint of your spectrogram-generating model (alternatively, you can use my pretrained models). The checkpoint contains also the the hyper-parameters you specified using the `hyper_parameter` when training.
According to the `dataset` parameter (now stored in the checkpoint, so it does not have to be the default value, i.e., `ljspeech`, see [this procedure](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/e01fa7899b7570306df3e7bac72ced9958ca85e8/utils/__init__.py#L29)), GTA instantiates the dataset, iterates through contained train examples and generates GTA spectrograms.  

I think that this is the typical use-case because you want to train both models with the same data, isn't it? You can of course change [this line ](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/e01fa7899b7570306df3e7bac72ced9958ca85e8/gta.py#L56)  and add a new argument to the `gta.py` script.

You are totally right about the names. I am sorry that it is not directly and easily usable. I experimented with more vocoder implementations besides this WaveRNN implementation (forked), so it is kind of a messed ... It requires some renaming, copying or moving of the files.

The `gta.py` script iterates through the `train` subset of you dataset in the order as listed in the dataset's meta-file (I suppose it is named `train.txt`).  So the generated GTA spectrogram with the lowest ID should correspond to the `.wav` from the first line of the meta-file (note that the script could have skipped some lines because of the `--speakers` argument) and so on. I was using a shell one-liner to move and rename the files.

I am really sorry for this inconvenience :disappointed_relieved:

**Comment by anselmerobert** [comment]
Ok I understand.
My mistake for the hyper_parameters, I haven't seen that they were also in the checkpoint.
Thanks a lot for the explanations.
I still have two more remark/questions :
- when I ran the gta.py script as it is I got an error "type object 'Params' has no attribute 'unique_speakers'", so I commented [the lines concerning the speakers filtering](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/e01fa7899b7570306df3e7bac72ced9958ca85e8/gta.py#L59-L61) to make it run.
- I got 15150 gta mel files out of 57163 wav files in the train.txt file for css10, I guess this is because of the balanced_sampling/perfect_sampling parameters set to true ?
Thanks again

**Comment by Tomiinek** [comment]
Hmm, I am quite surprised that the attribute is not present. It should have been set on [this line](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/4f7df17fc6f8f154bbb172225e9657b952824476/train.py#L243) :disappointed_relieved: But removing the lines you mentioned should work.

This is also surprising, but you are right, the perfect sampler might be the cause. The number of batches it produces depends on (if I remember correctly :smile: ) the number of examples in the less frequent language, which is Greek. Removing [this branch](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/e01fa7899b7570306df3e7bac72ced9958ca85e8/gta.py#L64-L68)  and using a regular sampler should be sufficient? You can also try setting batch size 1 or something really low.

Again, I am sorry for that. It seems that the `gta.py` script is made of spaghetti ...

**Comment by leijue222** [comment]
@Tomiinek Hi, how do I generate train.txt for my own dataset? 
Write the script by myself or modify which of your .py files?

**Comment by vince62s** [comment]
@Tomiinek out of curiosity. did you try to train the WaveRNN part on Melspectrograms directly instead of GTA ? if so was it really worse than on GTA ?
thanks.

**Comment by leijue222** [comment]
> @Tomiinek out of curiosity. did you try to train the WaveRNN part on Melspectrograms directly instead of GTA ? if so was it really worse than on GTA ? thanks.

On the contrary, I did not use GTV mode to train WAVERNN and got good results.
